### ISSUE TITLE
year field validation issue

### ISSUE THREAD

**Issue by GetIbetsamAhmed** [GetIbetsamAhmed/Angular-Recipe-MoviesList#2]
this.formGroup = this.formBuilder.group({
      year: [
        "",
        Validators.compose([
          Validators.required,
          Validators.maxLength(40),
          Validators.minLength(4),
        ]),
      ],
    });
  }

in this year field we need to min and max both are 4 digits

**Comment by IbtesamTech** [comment]
Issue resolved and pushed to main branch

**Comment by GetIbetsamAhmed** [comment]
Issue merged
